# Generated by Django 4.0.4 on 2022-04-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikipedia', '0003_project_is_tokenized_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='translated_sentence',
            field=models.CharField(default='No Translation Found (Add your translation here)', max_length=5000),
        ),
    ]
