# Generated by Django 4.0.4 on 2022-04-27 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wikipedia', '0004_alter_sentence_translated_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='annotator_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotator_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
