# Generated by Django 4.0.4 on 2022-04-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikipedia', '0006_rename_annotator_id_project_annotator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='translated_sentence',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
